defaults:
  - base
  - _self_

command: 
  - "/time set night"

task_conf:
  - name: "bread"
    text: "craft_item:bread" 

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "bread"
    identity: "craft bread"
  
init_inventory: 
  - slot: 0
    type: crafting_table
    quantity: 1

  - slot: "random"
    type: "wheat"
    quantity: ">9"
  - slot: "random"
    type: "wheat"
    quantity: ">9"

need_crafting_table: True
need_gui: True

inventory_distraction_level: "zero"