defaults:
  - base
  - _self_

command: 
  - "/time set night"

task_conf:
  - name: "crafting_table"
    text: "craft_item:crafting_table" 

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "crafting_table"
    identity: "craft crafting_table"
  
init_inventory: 
  - slot: "random"
    type: "oak_planks"
    quantity: ">3"
  - slot: "random"
    type: "oak_planks"
    quantity: ">3"

need_crafting_table: False
need_gui: True

inventory_distraction_level: "zero"