defaults:
  - base
  - _self_

command: 
  - "/time set day"
  
task_conf:
  - name: "pig"
    text: "kill_entity:pig"
    task_id: 11
  - name: "cooked_porkchop"
    text: "craft_item:cooked_porkchop" 
    task_id: 17

reward_conf:
  - event: "kill_entity"
    max_reward_times: 100
    reward: 0.1
    objects: 
      - "pig"
    identity: "kill pig"
  - event: "craft_item"
    max_reward_times: 100
    reward: 1.0
    objects: 
      - "cooked_porkchop"
    identity: "craft cooked_porkchop"

mobs: 
  - name: "pig"
    number: 1
    range_x:  [-2, 2]
    range_z:  [3, 10]

init_inventory: 
  - slot: 0
    type: "diamond_sword"
    quantity: 1

  - slot: 1
    type: "furnace"
    quantity: 1

  - slot: 2
    type: "coal"
    quantity: ">24"
  - slot: "random"
    type: "coal"
    quantity: ">24"
