defaults:
  - base
  - _self_

seed: 27

command: 
  - "/time set night"
  - '/tp @s 133 61 2'

task_conf:
  - name: "mine"
    text: "mine_block:stone" 

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "stone"
    identity: "mine stone"

init_inventory: 
  - slot: 0
    type: "iron_pickaxe"
    quantity: 1
  - slot: 1
    type: "iron_shovel"
    quantity: 1
