defaults:
  - base
  - _self_

seed: 100

command: 
  - "/time set night"
  - '/tp @s -216 72 202'

task_conf:
  - name: "mine"
    text: "mine_block:oak_log" 

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "oak_log"
    identity: "mine oak_log"

init_inventory: 
  - slot: 0
    type: "iron_pickaxe"
    quantity: 1
  - slot: 1
    type: "iron_shovel"
    quantity: 1
