defaults:
  - base
  - _self_

seed: 1

command: 
  - "/time set night"
  - '/tp @s 17950 11 7506'

task_conf:
  - name: "mine"
    text: "mine_block:gold_ore" 

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "gold_ore"
    identity: "mine gold_ore"

init_inventory: 
  - slot: 0
    type: "iron_pickaxe"
    quantity: 1
  - slot: 1
    type: "iron_shovel"
    quantity: 1
